[appendix]
== Why 3D Print Weapons
It is the imperative of every living thing to defend itself.
That means it's up to you to fight back when something tries to eat you.
It's nobody else's responsibility, and even if it were - YOU are your own
first responder. Get help if you can, but sometimes no help is coming.

Weapons are the means by which we can defend ourselves.
They are force multipliers, it's how a 95lb grandmother can fight off a
300lb linebacker.

Let this be a light for dark times.

=== No Step
The 2-inch-long Golden Poison Dart Frog's skin contains a toxin so deadly
it can kill over a dozen adults. But they'd all have to touch it.
Rosebushes and rattlesnakes get along like hemlock and honeybees.
Harmless and helpless are worlds apart.

Ultimately, self-defense is an individual imperative.
I mean no harm to anyone who would leave me alone; I'm live-and-let-live.
But I choose not to be a subject, an easy target, or a helpless victim.
Let us trade stories, good times, food, jeans, and genes.
Go in peace and prosper. Failing that - leave me alone or else.

=== What About Murderers?
It should go without saying that I find murder detestable.
It's my desire to arm those intent on self-defense, not murderers.

Weapons are tools, and it is for the user to use them responsibly. On balance,
I expect far more non-murderers to make these weapons than murderers.

==== What About Terrorists?
The US Government gave them billions of dollars worth of state-of-the-art
weapons and equipment when it left Afghanistan. Most of the world's terrorists
were armed by governments to fight proxy wars and yesterday's terrorists.

That's not who's going to be building these weapons.

==== What About Mass Shooters?

Most definitions of "mass shooting" use something along the lines of 3+ people.
My objections to this definition notwithstanding,
don't miss the forest for the trees.

Nation states have body counts in the tens of millions,
with precedents in living memory.
Mass murderers don't hold a candle to the murderous capacity of a state.
When a state is murdering it's own people, that's a Tuesday.

=== Bigger Fish to Fry
I do this to spread the capacity for self-defense. My greatest concern is 
states that murder their own people, and civilian disarmament only helps them.

The great https://en.wikipedia.org/Democide[democides] and
https://en.wikipedia.org/wiki/List_of_wars_by_death_toll[wars]
in living memory have demonstrated the need for individually held arms.

You might die fighting, fight like hell anyway.
Compliance might be the death of you.

==== The "Banality of Evil"
The *second* greatest danger to human prosperity and life is the order giver.
Stalin, Hitler, and Mao never personally murdered anyone.
Neither did Charles Manson or Jim Jones for that matter.

The greatest danger is the unquestioning order-follower.
Nothing more than a cog in a machine.

 1. Enforce the current government's current laws, even if they are atrocious.
 2. Fight the current government's enemies, even if manufactured or imagined.

"Befehl ist Befehl" is German for "an order is an order."
Nazis used this explanation in the Nuremberg trials to excuse their murders.
"I was just following orders" they said.

You can be murdered by a normal person just doing their job.
That person might be an upstanding patriot wearing their (or your) country's
flag and enforcing the law - following lawful orders to murder you.

See also: https://en.wikipedia.org/wiki/Hannah_Arendt[Hannah Arendt]

==== What About Drones, Jets, Tanks, and Nukes?
The idea that a government would nuke its own territory is laughable.
I think the spirit of this question boils down to "but you're outgunned."

My short answer to that is "maybe."
If I _am_ outgunned, that's hardly an argument to just lie down and take it.
I refuse to put myself at the mercy of anyone who would threaten me with
destruction for having the audacity to fight back and protect myself.

The other side of that coin is "maybe not."
The greatest military superpower in the history of the world has a notoriously
hard time dealing with insurgencies. I don't have to fight a tank if I can run
away from it, and kill the driver when he comes out to eat or sleep.
Read up a bit on https://en.wikipedia.org/wiki/Guerrilla_warfare[Guerrilla Warfare].

<<<
=== Selected Quotes

> A man's natural rights are his own, against the whole world; and any infringement of them is equally a crime; whether committed by one man, or by millions; whether committed by one man, calling himself a robber, or by millions calling themselves a government.

Lysander Spooner, No Treason: The Constitution of No Authority

---

> And how we burned in the camps later, thinking: What would things have been like if every Security operative, when he went out at night to make an arrest, had been uncertain whether he would return alive and had to say good-bye to his family? Or if, during periods of mass arrests, as for example in Leningrad, when they arrested a quarter of the entire city, people had not simply sat there in their lairs, paling with terror at every bang of the downstairs door and at every step on the staircase, but had understood they had nothing left to lose and had boldly set up in the downstairs hall an ambush of half a dozen people with axes, hammers, pokers, or whatever else was at hand?... The Organs would very quickly have suffered a shortage of officers and transport and, notwithstanding all of Stalin's thirst, the cursed machine would have ground to a halt! If...if...We didn't love freedom enough. And even more - we had no awareness of the real situation.... We purely and simply deserved everything that happened afterward.

Aleksandr I. Solzhenitsyn , The Gulag Archipelago 1918-1956
