version: 0.2

batch:
  fast-fail: true

phases:
  install:
    on-failure: ABORT
    commands:
      - add-apt-repository -y ppa:openscad/releases
      - apt-get update
      - apt install -y xvfb openscad cmark-gfm imagemagick ffmpeg bc parallel jq 
  build:
    on-failure: ABORT
    commands:
      - make -j -o -l 2.5 all dist
artifacts:
  files:
    - '**/*'
  name: Liberator12k.zip
  discard-paths: no
  base-directory: dist
