version: 0.2

batch:
  fast-fail: true

phases:
  install:
    on-failure: ABORT
    commands:
      - add-apt-repository -y ppa:openscad/releases
      - apt-get update
      - apt install -y xvfb openscad cmark-gfm imagemagick ffmpeg bc parallel jq htmldoc moreutils
  build:
    on-failure: ABORT
    commands:
      - xvfb-run -f .Xauthority -n 99 -s "-screen 0 1920x1080x24 +extension GLX +render -noreset" sleep infinity &
      - env DISPLAY=:99 XAUTHPROTO=. XAUTHORITY=`pwd`/.Xauthority make -k -j -Otarget -l 2.5 all || true
      - env DISPLAY=:99 XAUTHPROTO=. XAUTHORITY=`pwd`/.Xauthority make -j -Otarget -l 2.5 all
artifacts:
  files:
    - '**/*'
  name: Liberator12k.zip
  discard-paths: no
  base-directory: .
cache:
  paths:
    - Receiver/**/*
