include ../../Makefile.in
include ../STL.mk
include ../Animation.mk

ANIMATIONS=.animations/FCG.mp4

TARGETS=$(EXPORTS) $(ASSEMBLIES) $(ANIMATIONS)

clean-dir:
	rm -rf $(ASSEMBLY_DIR) $(BUILD_DIR) $(EXPORT_DIR)

all: $(SUBDIRS) $(TARGETS)

