== Why
It is the imperative of every living thing to defend itself.
That means it's up to you to fight back when something tries to eat you.

Get help if you can, but sometimes no help is coming.
Let this be a light for dark times.

=== No Step
The 2-inch-long Golden Poison Dart Frog's skin contains a toxin so deadly
it can kill over a dozen adults. But they'd all have to touch it.
Rosebushes and rattlesnakes get along like hemlock and honeybees.
Harmless and helpless are worlds apart.

Let us trade stories, good times, food, jeans, and genes.
Go in peace and prosper. Failing that - leave me alone or else.

=== Bigger Fish to Fry
The great [democides](https://en.wikipedia.org/Democide) and
[wars](https://en.wikipedia.org/wiki/List_of_wars_by_death_toll)
in living memory have demonstrated the need for individually held arms.

If history repeats itself, complying might be the death of you.
So like the honeybee - fight like hell anyway.

==== The "Banality of Evil"
The *second* greatest danger to human prosperity and life is the order giver.
Stalin, Hitler, and Mao never personally murdered anyone.
Neither did Charles Manson or Jim Jones for that matter.

The greatest danger is the unquestioning order-follower.
Nothing more than a cog in a machine.

 1. Enforce the current government's current laws, even if they are atrocious.
 2. Fight the current government's enemies, even if manufactured or imagined.

"Befehl ist Befehl" is German for "an order is an order."
Nazis used this explanation in the Nuremberg trials to excuse their murders.
"I was just following orders" they said.

**Takeaway**: You can be murdered by a normal person just going about their day.
That person might be an upstanding patriot wearing your country's flag and
enforcing the law - following lawful orders to murder you.

See also: [Hannah Arendt](https://en.wikipedia.org/wiki/Hannah_Arendt)

===== Murder Machine
I'm a software engineer, it's a lens through which I see the world.
I see nation states which run like mindless machines.
Code written by lawyers running on flawed human beings doing their part.
Its ultimate tool: violence - to death. And nobody knows this is a machine.

===== What About Mass Shooters?
Most definitions of "mass shooting" use something along the lines of 3+ people.

Nation states have body counts in the tens of millions,
with precedents in living memory.
When a state is murdering it's own people, that's a Tuesday morning in BFE.
An event so routine and monotonous that they make up games to spice things up.

Don't miss the forest for the trees.

===== What About Terrorists?
The US Government gave them billions of dollars worth of equipment way better
than this when it left Afghanistan.

==== What About Tanks and Nukes?
Read up a bit on [Guerrilla Warfare](https://en.wikipedia.org/wiki/Guerrilla_warfare) tactics.

And 3D printed nukes.

=== Some other thoughts of others

> A man's natural rights are his own, against the whole world; and any infringement of them is equally a crime; whether committed by one man, or by millions; whether committed by one man, calling himself a robber, or by millions calling themselves a government.

Lysander Spooner, No Treason: The Constitution of No Authority

---

> My political opinions lean more and more to Anarchy (philosophically understood, meaning abolition of control not whiskered men with bombs) - or to 'unconstitutional' Monarchy. I would arrest anybody who uses the word State (in any sense other than the inanimate realm of England and its inhabitants, a thing that has neither power, rights nor mind); and after a chance of recantation, execute them if they remained obstinate! If we could get back to personal names, it would do a lot of good. Government is an abstract noun meaning the art and process of governing and it should be an offence to write it with a capital G or so as to refer to people. If people were in the habit of referring to 'King George's council, Winston and his gang', it would go a long way to clearing thought, and reducing the frightful landslide into Theyocracy.

The Letters of J.R.R. Tolkien, pg. 74, Letter 52.

---

> And how we burned in the camps later, thinking: What would things have been like if every Security operative, when he went out at night to make an arrest, had been uncertain whether he would return alive and had to say good-bye to his family? Or if, during periods of mass arrests, as for example in Leningrad, when they arrested a quarter of the entire city, people had not simply sat there in their lairs, paling with terror at every bang of the downstairs door and at every step on the staircase, but had understood they had nothing left to lose and had boldly set up in the downstairs hall an ambush of half a dozen people with axes, hammers, pokers, or whatever else was at hand?... The Organs would very quickly have suffered a shortage of officers and transport and, notwithstanding all of Stalin's thirst, the cursed machine would have ground to a halt! If...if...We didn't love freedom enough. And even more - we had no awareness of the real situation.... We purely and simply deserved everything that happened afterward.

Aleksandr I. Solzhenitsyn , The Gulag Archipelago 1918-1956
